blog/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blogapp.urls')),
    path('users/', include('users.urls')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_URL)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blogapp/urls.py
from django.urls import path, include
from django.views.decorators.http import require_POST

from . import views


app_name = 'blogapp'
urlpatterns = [
    path('blog-list/', views.BlogListView.as_view(), name='list'),
    path('<slug:slug>/', views.DetailBlogView.as_view(), name='post'),
    # path('my_form/', require_POST(views.CommentFormView.as_view()), name='comment_form'),
    path('', views.index, name='index'),
]

blogapp/models.py
from django.db import models
from django.db.models.signals import pre_save
from django.db.models import Count
from django.urls import reverse

from users.models import User
from .utils import unique_slug_generator

from taggit.managers import TaggableManager


class BlogQuerySet(models.query.QuerySet):
    """Personalized queryset created to improve model usability"""

    def get_5_popular_post(self):
        """Returns only the popular items as in the current queryset."""
        return self.order_by('-views')[:5]

    def get_popular_post(self):
        """Returns only the popular items as in the current queryset."""
        return self.filter(status="P").order_by('-views', '-timestamp')

    def get_counted_tags(self):
        tag_dict = {}
        query = self.annotate(
            tagged=Count('tags')).filter(tags__gt=0)
        for obj in query:
            for tag in obj.tags.names():
                if tag not in tag_dict:
                    tag_dict[tag] = 1

                else:  # pragma: no cover
                    tag_dict[tag] += 1

        return tag_dict.items()


class Category(models.Model):
    title = models.CharField(max_length=100)
    slug = models.SlugField(unique=True, null=True, blank=True)

    def __str__(self):
        return self.title


class Blog(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField(max_length=200)
    slug = models.SlugField(max_length=80, null=True, blank=True)
    content = models.TextField()
    timestamp = models.DateTimeField(auto_now_add=True)
    views = models.PositiveIntegerField(null=True, blank=True)
    categories = models.ForeignKey(Category, on_delete=models.CASCADE)
    thumbnail = models.ImageField(upload_to='blog/', default='img/blog-1.jpg')
    tags = TaggableManager()
    objects = BlogQuerySet.as_manager()

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('blogapp:post', kwargs={'slug': self.slug})


class Comment(models.Model):
    blog = models.ForeignKey(Blog, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    comment = models.CharField(max_length=250)
    timestamp = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.blog.title


def blog_pre_save_receiver(sender, instance, *args, **kwargs):
    if not instance.slug:
        instance.slug = unique_slug_generator(instance)


pre_save.connect(blog_pre_save_receiver, sender=Blog)


def category_pre_save_receiver(sender, instance, *args, **kwargs):
    if not instance.slug:
        instance.slug = unique_slug_generator(instance)


pre_save.connect(category_pre_save_receiver, sender=Category)

templates/blog.html
{% extends "base.html" %}
{% load static humanize %}
{% block content %}

    <div class="container">
      <div class="row">
        <!-- Latest Posts -->
        <main class="posts-listing col-lg-8"> 
          <div class="container">
            <div class="row">
              <!-- post -->
              {% for blog in blogs %}                
                <div class="post col-xl-6">
                    <div class="post-thumbnail"><a href="{{ blog.get_absolute_url }}"><img src="{{ blog.thumbnail.url }}" alt="..." class="img-fluid"></a></div>
                    <div class="post-details">
                      <div class="post-meta d-flex justify-content-between">
                        <div class="date meta-last">{{ blog.timestamp|date:"d M | Y" }}</div>
                        <div class="category"><a href="#">{{ blog.categories }}</a></div>
                      </div><a href="{{ blog.get_absolute_url }}">
                        <h3 class="h4">{{ blog.title }}</h3></a>
                      <p class="text-muted">{{ blog.content|truncatechars:120 }}.</p>
                      <footer class="post-footer d-flex align-items-center"><a href="#" class="author d-flex align-items-center flex-wrap">
                          {% if blog.user.picture %}
                            <div class="avatar"><img src="{{ blog.user.picture.url }}" alt="..." class="img-fluid"></div>
                          {% else %}
                            <div class="avatar"><img src="{% static 'img/small-thumbnail-3.jpg' %}" alt="..." class="img-fluid"></div>
                          {% endif %}
                          <div class="title"><span>{{ blog.user.get_profile_name }}</span></div></a>
                        <div class="date"><i class="icon-clock"></i> {{ blog.timestamp|naturaltime }}</div>
                        <div class="comments meta-last"><i class="icon-comment"></i>{{ blog.comment_set.all.count }}</div>
                      </footer>
                    </div>
                </div>
              {% empty %}
              <h3>No blogs </h3>
              {% endfor %}
          </div>
            <!-- Pagination -->
          {% if is_paginated %}
              <nav aria-label="Page navigation example">
                <ul class="pagination pagination-template d-flex justify-content-center">
                  {% if page_obj.has_previous %}
                    <li class="page-item"><a href="?page={{ page_obj.previous_page_number }}{% if request.GET.query %}&query={{ request.GET.query }}{% endif %}" class="page-link"> <i class="fa fa-angle-left"></i></a></li>
                  {% else %}
                    <li class="page-item disabled"><a href="?page={{ page_obj.previous }}" class="page-link"> <i class="fa fa-angle-left"></i></a></li>
                  {% endif %}

                  {% for page_num in paginator.page_range %}
                    {% if page_obj.number == page_num %}
                      <li class="page-item disabled"><a href="#" class="page-link active">{{ page_num }}</a></li>
                    {% elif page_num > page_obj.number|add:'-3' and page_num < page_obj.number|add:'3' %}
                    <li class="page-item"><a href="?page={{ page_num }}{% if request.GET.query %}&query={{ request.GET.query }}{% endif %}" class="page-link">{{ page_num }}</a></li>
                    {% endif %}
                  {% endfor %}
                  
                  {% if page_obj.has_next %}
                    <li class="page-item"><a href="?page={{ page_obj.next_page_number }}{% if request.GET.query %}&query={{ request.GET.query }}{% endif %}" class="page-link"> <i class="fa fa-angle-right"></i></a></li>
                  {% else %}
                    <li class="page-item disabled"><a href="#" class="page-link"> <i class="fa fa-angle-right"></i></a></li>
                  {% endif %}
                </ul>
              </nav>
            {% endif %}
        </main>
        <aside class="col-lg-4">
          {% include "search.html" %}
          <!-- Widget [Latest Posts Widget]        -->
          <div class="widget latest-posts">
            <header>
              <h3 class="h6">Latest Posts</h3>
            </header>

            <div class="blog-posts">
              {% for blog in latest_blog %}
                <a href="{% url 'blogapp:post' blog.slug %}">              
                <div class="item d-flex align-items-center">
                  <div class="image"><img src="{{ blog.thumbnail.url }}" alt="..." class="img-fluid"></div>
                  <div class="title"><strong>{{ blog.title }}</strong>
                    <div class="d-flex align-items-center">
                      <div class="views"><i class="icon-eye"></i> {{ blog.views }}</div>
                      <div class="comments"><i class="icon-comment"></i>{{ blog.comment_set.all.count }}</div>
                    </div>
                  </div>
                </div></a>
              {% endfor %}
            </div>
          </div>
          <!-- Widget [Categories Widget]-->
          <div class="widget categories">
            <header>
              <h3 class="h6">Categories</h3>
            </header>
            {% for category in categories %}
              <div class="item d-flex justify-content-between"><a href="#">{{ category.title }}</a><span>{{ category.blog_set.all.count }}</span></div>
            {% endfor %}
          </div>
          <!-- Widget [Tags Cloud Widget]-->
          <div class="widget tags">       
            <header>
              <h3 class="h6">Tags</h3>
            </header>
            <ul class="list-inline">
              {% for tag, count in popular_tags %}
                <li class="list-inline-item"><a href="#" class="tag">#{{ tag }} {{ count }}</a></li>
              {% endfor %}
            </ul>
          </div>
        </aside>
      </div>
    </div>

{% endblock %}

templates/post.html
{% extends "base.html" %}

{% load static humanize %}
{% block content %}
  </head>
  <body>
    <div class="container">
      <div class="row">
        <!-- Latest Posts -->
        <main class="post blog-post col-lg-8"> 
          <div class="container">
            <div class="post-single">
              <div class="post-thumbnail"><img src="{{ blog.thumbnail.url }}" alt="..." class="img-fluid"></div>
              <div class="post-details">
                <div class="post-meta d-flex justify-content-between">
                  <div class="category"><a href="#">{{ blog.categories }}</a></div>
                </div>
                <h1 id="title">{{ blog.title }}<a href="{% url 'blogapp:post' blog.slug %}#title"><i class="fa fa-bookmark-o"></i></a></h1>
                <div class="post-footer d-flex align-items-center flex-column flex-sm-row"><a href="#" class="author d-flex align-items-center flex-wrap">
                    <div class="avatar"><img src="{{ blog.user.picture.url }}" alt="..." class="img-fluid"></div>
                    <div class="title"><span>{{ blog.user.get_profile_name }}</span></div></a>
                  <div class="d-flex align-items-center flex-wrap">       
                    <div class="date"><i class="icon-clock"></i> {{ blog.timestamp|naturaltime }}</div>
                    <div class="views"><i class="icon-eye"></i> {{ blog.views }}</div>
                    <div class="comments meta-last"><i class="icon-comment"></i>{{ blog.comment_set.all.count }}</div>
                  </div>
                </div>
                <div class="post-body">
                  {{ blog.content }}
                </div>
                
                <div class="post-tags">{% for tags in blog.tags.all %}<a href="#" class="tag">#{{ tags }}</a>{% endfor %}</div>                      
                
                <div class="posts-nav d-flex justify-content-between align-items-stretch flex-column flex-md-row">
                  {% if blog.get_previous_by_timestamp %}
                  <a href="{% url 'blogapp:post' blog.get_previous_by_timestamp.slug %}"class="prev-post text-left d-flex align-items-center">
                    <div class="icon prev"><i class="fa fa-angle-left"></i></div>
                    <div class="text"><strong class="text-primary">Previous Post </strong>
                      <h6>{{ blog.get_previous_by_timestamp.title }}.</h6>
                    </div></a>
                    {% endif %} 
                    {% if blog.get_next_by_timestamp %}
                    <a href="{% url 'blogapp:post' blog.get_next_by_timestamp.slug %}" class="next-post text-right d-flex align-items-center justify-content-end">
                    <div class="text"><strong class="text-primary">Next Post </strong>
                      <h6>{{ blog.get_next_by_timestamp.title }}.</h6>
                    </div>
                    <div class="icon next"><i class="fa fa-angle-right">   </i></div></a>
                  {% endif %}</div>
                <div class="post-comments">
                  <header>
                    <h3 class="h6">Post Comments<span class="no-of-comments">({{ blog.comment_set.all.count }})</span></h3>
                  </header>
                  <div class="comment">
                    {% for comment in blog.comment_set.all %}
                      <div class="comment-header d-flex justify-content-between">
                        <div class="user d-flex align-items-center">
                          <div class="image"><img src="{{ comment.user.picture.url }}" alt="..." class="img-fluid rounded-circle"></div>
                          <div class="title"><strong>{{ comment.user.get_profile_name }}</strong><span class="date">{{ comment.timestamp|date:"M Y" }}</span></div>
                        </div>
                      </div>
                      <div class="comment-body">
                        <p>{{ comment.comment }}.</p>
                      </div>
                    {% endfor %}
                  </div>
                </div>
                <div class="add-comment">
                  <header>
                    <h3 class="h6">Leave a reply</h3>
                  </header>
                  <form action="" class="commenting-form" method="POST" novalidate>
                    <div class="row">
                      <div class="form-group col-md-6">
                        <input type="text" value="{{ request.user.username }}" name="username" id="username" placeholder="Name" class="form-control">
                      </div>
                      <div class="form-group col-md-6">
                        <input type="email" value="{{ request.user.email }}" name="username" id="useremail" placeholder="Email Address (will not be published)" class="form-control">
                      </div>
                      <div class="form-group col-md-12">
                        {% csrf_token %}
                        {{ form }}
                      </div>
                      <div class="form-group col-md-12">
                        <button type="submit" class="btn btn-secondary">Submit Comment</button>
                      </div>
                    </div>
                  </form>
                </div>
              </div>
            </div>
          </div>
        </main>
        <aside class="col-lg-4">
          {% include "search.html" %}
          <!-- Widget [Latest Posts Widget]        -->
          <div class="widget latest-posts">
            <header>
              <h3 class="h6">Latest Posts</h3>
            </header>
            
            <div class="blog-posts">
              {% for blog in latest_blog %}
                <a href="{% url 'blogapp:post' blog.slug %}">              
                <div class="item d-flex align-items-center">
                  <div class="image"><img src="{{ blog.thumbnail.url }}" alt="..." class="img-fluid"></div>
                  <div class="title"><strong>{{ blog.title }}</strong>
                    <div class="d-flex align-items-center">
                      <div class="views"><i class="icon-eye"></i> {{ blog.views }}</div>
                      <div class="comments"><i class="icon-comment"></i>{{ blog.comment_set.all.count }}</div>
                    </div>
                  </div>
                </div></a>
              {% endfor %}
            </div>
          </div>
          <!-- Widget [Categories Widget]-->
          <div class="widget categories">
            <header>
              <h3 class="h6">Categories</h3>
            </header>
            {% for category in categories %}
              <div class="item d-flex justify-content-between"><a href="#">{{ category.title }}</a><span>{{ category.blog_set.all.count }}</span></div>
            {% endfor %}
          </div>
          <!-- Widget [Tags Cloud Widget]-->
          <div class="widget tags">       
            <header>
              <h3 class="h6">Tags</h3>
            </header>
            <ul class="list-inline">
              {% for tags in blog.tags.all %}
                <li class="list-inline-item"><a href="#" class="tag">#{{ tags }}</a></li>
              {% endfor %}
            </ul>
          </div>
        </aside>
      </div>
    </div>
{% endblock content %}

templates/search.html
<!-- Widget [Search Bar Widget]-->
          <div class="widget search">
            <header>
              <h3 class="h6">Search the blog</h3>
            </header>
            <form action="{% url 'blogapp:list' %}" class="search-form">
              <div class="form-group">
                <input name="query" type="search" value="{{ request.GET.query }}" placeholder="What are you looking for?">
                <button type="submit" class="submit"><i class="icon-search"></i></button>
              </div>
            </form>
          </div>